# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "##vso[task.logissue type=warning;sourcepath=azure-pipelines.yml;linenumber=12;columnnumber=1;code=warncode;]Found a warning from pipeline 2."
    echo "##vso[task.logissue type=error;sourcepath=azure-pipelines.yml;linenumber=10;columnnumber=1;code=errcode;]Found an error from pipeline 2."
  displayName: 'Run a multi-line script'

